### ISSUE TITLE
DR0012: Severe issue when sharing data with Rust FFI functions

### ISSUE THREAD

**Issue by chuigda** [Pr47/doc47#14]
### Describe the issue
According to [`[pr47.ffi.func/1]`](https://github.com/Pr47/doc47/blob/master/src/cha6-ffi.md#62--binding-rust-function-pr47ffifunc):

> An implementation must be able to register any Rust function whose parameter types satisfy one of the following rules:
> - ...
> - `&'a T` or `&'a mut T`, where 'a outlives the lifetime of the Pr47 instance (if applicable), and `T: 'static`

And according to [`[pr47.ffi.func/2]`]():

> for parameter with `&'a T` type, share Pr47 object with Rust environment
> for parameter with `&'a mut T` type, mutably share Pr47 object with Rust environment

And in the current de-facto standard, the Pr47 object is only temporarily shared between Pr47 environment and Rust FFI function. Giving user the right to create `&'a T` or `&'a mut T` would allow them to bind the following Rust function:

```rust
use std::cell::RefCell;

fn foo<'a>(cell: &'a RefCell<&'a i32>, r: &'a i32) {
    cell.replace(r);
}

fn bar<'a>(opt: &'a mut Option<&'a i32>, r: &'a i32) {
    opt.replace(r);
}
```

------

### Suggested fix
- We can use another lifetime `'b` which is strictly shorter than `'a`. However the T10 team met quite difficulty when doing so.
- We can use `Ref` types and `RefMut` types, just like what `RefCell` does. This makes our language more sound, but less conventient.

------

### See also
#12

**Comment by chuigda** [comment]
**[MID]** According to the talk with schungx the maintainer of Rhai, we've found that it is difficult (almost impossible) to support reference parameters, `T: 'a` andd `Fn: 'a` all together. By this time,

> **[schungx]**: I'd expect that the major problem with references will be to deal with lifetimes.  Right now Rhai cheats by making all functions 'static.   That means you can never return something that contains a reference unless it is 'static.

In fact, even in Rhai, without certain restrictions there can be problems:

```rust
fn unsound<'a>(orig: &'a mut i64) {
    let the_cell: RefCell<&'a mut i64> = RefCell::new(orig);
    let unsound_closure = |r: &'a mut i64| {
        the_cell.replace(r);
    };    
    // rhai.register(unsound_closure);
}
```

If the `register` function does not restrict the function to be `'static`, the code above can silently create a dangling pointer. As a result the binding of Rhai is limited. Such limitations can also be used by Pr47 to improve the overall soundness.

**Comment by chuigda** [comment]
**[MID]** Adding restrictions will make our language less powerful. But the language itself must be safe and sound for use, and then we can talk about its power.

**Comment by chuigda** [comment]
**[JUG]** An exception is the `Vec`, which is not `'static` by this time. It can be resolved at some specialization layer, I think.

**Comment by chuigda** [comment]
The implementation T10 has almost fixed this problem by adding extra lifetime requirements specified above. We can add that to our documentation soon, and close this defect report.

**Comment by SchrodingerZhu** [comment]
that sounds great

**Comment by chuigda** [comment]
> that sounds great

You'll build a wall, a huge one?

**Comment by chuigda** [comment]
Resolved.
