### ISSUE TITLE
P0004: New type annotation grammar

### ISSUE THREAD

**Issue by chuigda** [Pr47/doc47#4]
### Abstract
According to our investigation, most users prefer the following grammar

```go
var x: int = 5;
var y: deduced = x;
func foo(a: int, b: int): string;
```

instead of

```go
var x int = 5;
var y deduced = x;
func foo (a int, b int) string;
```

This proposal proposes the change of type annotation grammar.

**Comment by ICEYSELF** [comment]
**[Anqur]** voted for `var x int`

**Comment by chuigda** [comment]
**[Anqur]** **[Chuigda]** **[SmithGeorge]** voted for `var x int`

**Comment by ICEYSELF** [comment]
**[Hoshino]** voted for `var x: int`

**Comment by chuigda** [comment]
**[Hoshino]** **[Lyzh]** **[Miko]** **[Sepush]** **[Bottle]** **[Squirrel]** **[Lambda]** **[ice1000]** voted for `var x: int`

**Comment by chuigda** [comment]
**[MID]** As far as I see, it is in fact possible for us to place type declaration before the variable name, like
```c
int x = 5;
```

**Comment by chuigda** [comment]
> **[MID]** As far as I see, it is in fact possible for us to place type declaration before the variable name, like
> 
> ```c
> int x = 5;
> ```

**[JUG]** That "implementation" is ugly. We do prefer clean implementations.

**Comment by chuigda** [comment]
**[MID]** Enough already.

**Comment by chuigda** [comment]
没想到吧，你们双赢
![图片](https://user-images.githubusercontent.com/29348140/144533642-3f04f9fc-5e42-4188-866c-c102356544a1.png)
